### ISSUE TITLE
Tìm hiểu thế nào là xử lý video

### ISSUE THREAD

**Issue by leduclong2002** [leduclong2002/video-editing#1]

**Comment by DinhBui1** [comment]
Xử lý video là quá trình chỉnh sửa, biên tập hoặc đổi định dạng các tập tin video để tạo ra một sản phẩm video hoàn chỉnh. Các công việc xử lý video bao gồm cắt ghép video, chèn hiệu ứng, chỉnh sửa âm thanh, thêm chữ viết, cân bằng màu sắc, tăng độ phân giải, giảm nhiễu và nhiều tác vụ khác.
